/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedBillingRouteImport } from './routes/_authed.billing'
import { Route as AuthedIntakeServiceRecordIdRouteImport } from './routes/_authed.intake.$serviceRecordId'
import { Route as AuthedServicesSlugRouteImport } from './routes/_authed.services.$slug'
import { Route as ApiPaystackInitializeRouteImport } from './routes/api.paystack.initialize'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api.paystack.webhook'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntakeServiceRecordIdRoute =
  AuthedIntakeServiceRecordIdRouteImport.update({
    id: '/intake/$serviceRecordId',
    path: '/intake/$serviceRecordId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedServicesSlugRoute = AuthedServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiPaystackInitializeRoute = ApiPaystackInitializeRouteImport.update({
  id: '/api/paystack/initialize',
  path: '/api/paystack/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthedBillingRoute
  '/intake/$serviceRecordId': typeof AuthedIntakeServiceRecordIdRoute
  '/services/$slug': typeof AuthedServicesSlugRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/billing': typeof AuthedBillingRoute
  '/': typeof AuthedIndexRoute
  '/intake/$serviceRecordId': typeof AuthedIntakeServiceRecordIdRoute
  '/services/$slug': typeof AuthedServicesSlugRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/intake/$serviceRecordId': typeof AuthedIntakeServiceRecordIdRoute
  '/_authed/services/$slug': typeof AuthedServicesSlugRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/billing'
    | '/intake/$serviceRecordId'
    | '/services/$slug'
    | '/api/paystack/initialize'
    | '/api/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/billing'
    | '/'
    | '/intake/$serviceRecordId'
    | '/services/$slug'
    | '/api/paystack/initialize'
    | '/api/paystack/webhook'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invite'
    | '/login'
    | '/_authed/billing'
    | '/_authed/'
    | '/_authed/intake/$serviceRecordId'
    | '/_authed/services/$slug'
    | '/api/paystack/initialize'
    | '/api/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ApiPaystackInitializeRoute: typeof ApiPaystackInitializeRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/intake/$serviceRecordId': {
      id: '/_authed/intake/$serviceRecordId'
      path: '/intake/$serviceRecordId'
      fullPath: '/intake/$serviceRecordId'
      preLoaderRoute: typeof AuthedIntakeServiceRecordIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/$slug': {
      id: '/_authed/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof AuthedServicesSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/paystack/initialize': {
      id: '/api/paystack/initialize'
      path: '/api/paystack/initialize'
      fullPath: '/api/paystack/initialize'
      preLoaderRoute: typeof ApiPaystackInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedIntakeServiceRecordIdRoute: typeof AuthedIntakeServiceRecordIdRoute
  AuthedServicesSlugRoute: typeof AuthedServicesSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedIntakeServiceRecordIdRoute: AuthedIntakeServiceRecordIdRoute,
  AuthedServicesSlugRoute: AuthedServicesSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ApiPaystackInitializeRoute: ApiPaystackInitializeRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
